name: publish
on: [push]
jobs:
publish-docker-deploy-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/ApexPredatorTV/docker-deploy-demo:latest
       docker run ghcr.io/ApexPredatorTV/docker-deploy-demo:latest
       docker push ghcr.io/ApexPredatorTV/docker-deployr-demo:latest
